name: data_science_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - scipy
  - jupyter
  - jupyterlab
  - notebook
  - ipython
  - ipywidgets
  - tensorflow
  - keras
  - pytorch
  - torchvision
  - nltk
  - spacy
  - plotly
  - bokeh
  - xgboost
  - lightgbm
  - catboost
  - yellowbrick
  - joblib
  - tqdm
  - sqlalchemy
  - psycopg2
  - sqlite
  - cython
  - numba
  - dask
  - beautifulsoup4
  - lxml
  - requests
  - openpyxl
  - xlrd
  - pip
  - pip:
    - streamlit
    - fastapi
    - uvicorn
